# This is a basic workflow to help you get started with Actions
name: sample 
# Controls when the workflow will run
on:
  # Workflow executes when new commit happens on main within data factory publish folder
  push:
    branches:
      - '<ADF PUBLISH BRANCH NAME>'
    paths:
      - '<DEV ADF NAME>'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-uat-datafactory:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    environment: 
      name: <Environment Name>
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: '<ADF PUBLISH BRANCH NAME>'
      # Log into Azure
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
      - name: Deploy to Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: <UAT ADF ResourceGroup Name>
          dataFactoryName: <UAT ADF Name>
          armTemplateFile: ./<DEV ADF Name>/ARMTemplateForFactory.json
          armTemplateParametersFile: ./<DEV ADF Name>/arm_override/UAT_ParametersForFactory.json
