name: Terraform

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Terraform/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: 'Terraform'
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest
   
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
      with:
        terraform_version: 1.2.0
      
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: terraform init
      id: init
      run: terraform init    
    
    - name: plan
      run: |
         terraform plan    

    - name: apply
      run: terraform apply
